[package]
name = "liminal"
version = "0.2.1"
description = "An HTTP framework that make http processing easier, utilizing middleware pipelines"
repository = "https://github.com/edjcase/liminal"
keywords = ["http", "router", "parser", "middleware", "web", "pipeline"]
license = "MIT"

[dependencies]
new-base = "0.4.0"
itertools = "0.2.2"
xtended-text = "1.0.0"
xtended-numbers = "0.4.0"
asn1 = "2.0.2"
json = "1.3.0"
jwt = "1.1.0"
compression = "0.2.0"
serde = "3.2.2"
xml = "1.0.0"
http-assets = "0.0.8"
sha2 = "0.1.4"
url-kit = "0.0.9"

[dev-dependencies]
test = "2.1.1"
ic = "3.0.0"

[toolchain]
moc = "0.14.14"
