[package]
name = "liminal"
version = "0.2.1"
description = "An HTTP framework that make http processing easier, utilizing middleware pipelines"
repository = "https://github.com/edjcase/liminal"
keywords = [ "http", "router", "parser", "middleware", "web", "pipeline" ]
license = "MIT"

[dependencies]
new-base = "0.4.1"
itertools = "0.2.2"
xtended-text = "2.0.0"
xtended-numbers = "2.0.0"
asn1 = "3.0.1"
json = "1.4.0"
jwt = "2.0.1"
compression = "0.2.0"
serde = "3.3.2"
xml = "2.0.0"
http-assets = "0.0.9"
sha2 = "0.1.6"
url-kit = "1.0.1"
xtended-collections = "0.0.1"

[dev-dependencies]
test = "2.1.1"
ic = "3.2.0"

[toolchain]
moc = "0.14.14"
