[package]
name = "liminal"
version = "0.0.2"
description = "An HTTP framework that make http processing easier, utilizing middleware pipelines"
repository = "https://github.com/edjcase/liminal"
keywords = ["http", "router", "parser", "middleware", "web", "pipeline"]
license = "MIT"

[dependencies]
new-base = "0.4.0"
itertools = "0.2.2"
xtended-text = "1.0.0"
xtended-numbers = "0.4.0"
asn1 = "2.0.2"
json = "1.0.1"
jwt = "0.2.0"
compression = "0.2.0"
serde = "3.2.2"
xml = "1.0.0"
http-assets = "../ic-assets/src"

# Remove
base = "0.14.8"
http-types = "1.0.1"
map = "9.0.1"
certified-assets = "0.5.1"
ic = "2.0.0"
vector = "0.4.1"
encoding = "https://github.com/aviate-labs/encoding.mo#v0.4.1@2711d18727e954b11afc0d37945608512b5fbce2"
http-parser = "0.3.4"
sha2 = "0.1.2"
memory-region = "1.2.4"


[dev-dependencies]
test = "2.1.1"
ic = "2.0.0"
