[package]
name = "http"
version = "0.0.1"
description = "A collection of HTTP tools to make http requests easy to use"
repository = "https://github.com/edjcase/motoko_http"
keywords = [ "http", "router", "parser", "middleware", "web", "pipeline" ]
license = "MIT"

[dependencies]
new-base = "0.4.0"
itertools = "0.2.2"
json = "1.0.1"
xtended-text = "1.0.0"
xtended-numbers = "0.4.0"
glob = "0.0.1"
certified-assets = "0.5.1"
sha2 = "0.1.0"
ic-assets = "0.1.0"
base-x-encoder = "0.0.1"
hmac = "0.0.1"
ecdsa = "5.0.1"
asn1 = "2.0.2"

[dev-dependencies]
test = "2.1.1"
ic = "2.0.0"
