[package]
name = "liminal"
version = "2.0.0"
description = "An HTTP framework that make http processing easier, utilizing middleware pipelines"
repository = "https://github.com/edjcase/liminal"
keywords = ["http", "router", "parser", "middleware", "web", "pipeline"]
license = "MIT"

[dependencies]
"core@1" = "1.0.0"
"xtended-text@2" = "2.3.0"
"xtended-numbers@2" = "2.1.0"
"xtended-collections@0" = "0.2.0"
"json@1" = "1.4.0"
"jwt@2" = "2.1.1"
"compression@0" = "0.3.0"
"serde@3" = "3.3.2"
"xml@2" = "2.1.0"
"http-assets@0" = "0.2.0"
"sha2@0" = "0.1.6"
"url-kit@4" = "4.0.0"

[dev-dependencies]
test = "2.1.1"
ic = "3.2.0"
