[package]
name = "http-parser"
version = "0.0.1"
description = "An HTTP request parser to make http requests easy to use"
repository = "https://github.com/edjcase/motoko_http"
keywords = ["http", "parser"]
license = "MIT"

[dependencies]
xtended-text = "1.0.0"
itertools = "0.2.2"
