[package]
name = "http-router"
version = "0.1.0"
description = "An HTTP router to make http requests easy to use"
repository = "https://github.com/edjcase/motoko_http"
keywords = ["http", "router"]
license = "MIT"

[dependencies]
xtended-text = "1.0.0"
itertools = "0.2.2"
